### ISSUE TITLE
in continuous mode, asset filters are not applied upon 'refresh'

### ISSUE THREAD

**Issue by hburgund** [roundware/roundware-server#96]
When I put a project into 'continuous' repeat mode and then make certain filter selections to narrow down what I hear, I am getting incorrect recordings in the stream. It seems like when the repeat is triggered, the current filters are not applied. In other words, the filters seem to be applied initially, but when all available recordings are exhausted and the 'refresh' occurs, the current filters are not applied.

That's my best guess, but it's hard to tell. I looked at the logs and I see statements like this:

```
2012-05-21 21:39:03,223 recording_collection.py:71 DEBUG GET_RECORDING UPDATE:
all_recordings count: 1, far_recordings count: 0, nearby_played_recordings count: 0, nearby_unplayed_recordings count: 1
```

after I apply filters that should return 1 recording, and then when I look at the next similar statement to happen, based on the continuous mode refresh, it says:
```
2012-05-21 21:39:03,223 recording_collection.py:71 DEBUG GET_RECORDING UPDATE:
all_recordings count: 3, far_recordings count: 0, nearby_played_recordings count: 0, nearby_unplayed_recordings count: 3
```
ie. returns all available recordings.

thankfully, this is a bit of a fringe case currently since we are not actively using continuous mode, but I'm hoping it's fairly easy to remedy.

**Comment by eosrei** [comment]
This may have been fixed by fc956305b1e6f93c730c5c48311a0af6c258319c

@hburgund  Can you check?

**Comment by hburgund** [comment]
I just did a bunch of testing and I can't get ```continuous``` mode to work in any scenario.  I've tried in both geo-listen and global-listen modes, but I am not seeing the log printout that used to happen when there were no more assets available that indicated which mode was set, so I'm guessing that this check isn't happening anymore?  
IDK, this issue may indeed be fixed, but without ```continuous``` mode working, I can't test!

it seems this code isn't running for some reason: https://github.com/hburgund/roundware-server/blob/develop/roundwared/recording_collection.py#L86 ??

Am I doing something wrong in my tests?

**Comment by hburgund** [comment]
ok, bizarre; I need to test more, but want to note this recent testing behavior before I fall asleep.  I re-installed @eosrei ```schema-clean``` branch and continuous mode now works.  As soon as all playlist items are played, the whole thing resets and plays again, which is good.  

But the bug of not applying the tags to the playlist after the repeat still exists.  In other words, as soon as the assets re-fill the playlist in continuous mode, whatever tag filters that existed already are NOT applied again as they should be.

I will test more to see why continuous mode didn't work before and now does.  Very odd.
